minitwitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('twitter.urls', namespace='twitter')),
]

twitter/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^registro/', views.register, name='register'),
    url(r'^login/', views.login_user, name='login'),

]

twitter/models.py
from django.db import models


class User(models.Model):
	username = models.CharField('Username',max_length=50)
	email = models.EmailField()
	password = models.CharField('Password', max_length=50)

twitter/forms.py
from django import forms	

from django.contrib.auth.models import User

class NewForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ('first_name',
			'last_name',
			'username',
			'password',
			'email')


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		fields = ('username','password')

twitter/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login

from .forms import NewForm, LoginForm
from .forms import NewForm

def register(request):
	message = None
	if request.method == 'POST':
		form = NewForm(request.POST)
		if form.is_valid:
			username = request.POST['username']
			password = request.POST['password']
			email = request.POST['email']
			first_name = request.POST['first_name']
			last_name = request.POST['last_name']
			message = 'Usuario {} cadastrado com sucesso!'.format(username) 
			User.objects.create_user(
				username=username,
				password=password,
				email=email,
				first_name=first_name,
				last_name=last_name,
				is_active=True,
				is_staff=True,
				is_superuser=True
				)

	form = NewForm()
	return render(request, 'register.html', {'form':form, 'success_message':message})



def login_user(request):
	form = LoginForm()
	message = None
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(request, username=username, password=password)
			if user:
				login(request, user)
				message = 'Usuario {} está logado.'.format(username)
	return render(request, 'login.html', {'form':form, 'success_message':message})

twitter/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'login_files/bootstrap.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'login_files/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'login_files/signin.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'login_files/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
    {% if success_message %}     
    <script type="text/javascript">
        alert('{{success_message}}')
        
    </script>
    {% endif %}
      <form class="form-signin" action="{% url 'twitter:login' %}", method="POST">
      {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        {{ form }}
        <div class="checkbox">
          <label>
            <input value="remember-me" type="checkbox"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'login_files/ie10-viewport-bug-workaround.js'%}"></script>
  

</body></html>

twitter/templates/register.html
<!DOCTYPE html>
<html>
<head>
	<title>Register</title>
</head>
<body>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Registrar</button>
	</form>
	{% if success_message %}     
	<script type="text/javascript">
		alert('{{success_message}}')
		
	</script>
	{% endif %}
</body>
</html>